package ModelTrainLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class ConstraintsAspectDescriptor implements jetbrains.mps.smodel.runtime.ConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }
  public ConstraintsDescriptor getDescriptor(SConceptId conceptId) {
    long id = conceptId.getIdValue();
    if (id == 0x7b1e84e5f8af503aL) {
      return new Track_Constraints();
    }
    if (id == 0x16d2770f4d104340L) {
      return new TrackCurve_Constraints();
    }
    if (id == 0x7b1e84e5f8af503fL) {
      return new ModelTrainSet_Constraints();
    }
    if (id == 0x41f0eb9f5ea6264L) {
      return new TrackStraight_Constraints();
    }
    if (id == 0x41f0eb9f5ea6174L) {
      return new Station_Constraints();
    }
    if (id == 0x5e7da70e100fc394L) {
      return new Train_Constraints();
    }
    if (id == 0x41f0eb9f5ea6280L) {
      return new Route_Constraints();
    }
    return new BaseConstraintsDescriptor(conceptId);
  }
}
