package ModelTrainLanguage.behavior;

/*Generated by MPS */

import javax.swing.JComponent;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class ModelTrainSet_Behavior {
  public static JComponent call_createVisualisation_7539347229289352086(SNode __thisNode__) {
    return ModelTrainSet__BehaviorDescriptor.createVisualisation_id6yx95Kw7wIm(__thisNode__);
  }
  public static JComponent call_parseNodes_8271944451184038340(SNode __thisNode__) {
    return ModelTrainSet__BehaviorDescriptor.parseNodes_id7bbQqrm_D74(__thisNode__);
  }
}
