package ModelTrainLanguage.typesystem;

/*Generated by MPS */


public class Vector {
  /*package*/ float x;
  /*package*/ float y;
  /*package*/ float z;
  public Vector(float x, float y, float z) {
    this.x = x;
    this.y = y;
    this.z = z;
  }
}
