package ModelTrainLanguage.sandbox;

/*Generated by MPS */

import java.util.List;

public class TrackSegment {
  public String self;
  public List<Vector3> leftPoints;
  public List<Vector3> rightPoints;
  public String from;
  public String to;
  public double angle;
  public TrackSegment(String self, List<Vector3> leftPoints, List<Vector3> rightPoints, String from, String to, double angle) {
    this.self = self;
    this.leftPoints = leftPoints;
    this.rightPoints = rightPoints;
    this.from = from;
    this.to = to;
    this.angle = angle;
  }
}
