package ModelTrainLanguage.sandbox;

/*Generated by MPS */

import java.awt.image.AffineTransformOp;
import java.util.Queue;
import java.util.ArrayDeque;

public class Train {
  public RawImage trainImage;
  public RawImage[] carImages;
  public int[] carDistance;
  public String routeName;
  public int widthOriginal;
  public int heightOriginal;
  public int widthScaled;
  public int heightScaled;
  public Vector3 pos;
  public double rot;
  public AffineTransformOp op;
  public int xLoc;
  public int yLoc;
  public double scale;
  private boolean drawCars = false;
  public int currentPoint = 5;
  public int pointsFromTrackEdge = 5;
  private Queue<Pair<Vector3, Double>> positionalHistory = new ArrayDeque<Pair<Vector3, Double>>();

  public Train(String self, int nCars, String route) {
    routeName = route;
    trainImage = RawImage.createRawTrain();
    widthOriginal = trainImage.width;
    heightOriginal = trainImage.height;

    if (drawCars) {
      if (nCars > 0) {
        carImages = new RawImage[nCars];
        carDistance = new int[nCars];
        for (int i = 0; i < nCars; i++) {
        }
      }
    }
  }


}
