package ModelTrainLanguage.sandbox;

/*Generated by MPS */

import java.util.Queue;
import java.util.ArrayDeque;

public class Train {
  public RawImage trainImage;
  public RawImage[] carImages;
  public int[] carDistance;

  private boolean drawCars = false;
  private Queue<Pair<Vector3, Double>> positionalHistory = new ArrayDeque<Pair<Vector3, Double>>();

  public Train(int nCars) {
    trainImage = RawImage.createRawTrain();
    if (drawCars) {
      if (nCars > 0) {
        carImages = new RawImage[nCars];
        carDistance = new int[nCars];
        for (int i = 0; i < nCars; i++) {
        }
      }
    }
  }


}
