package ModelTrainLanguage.sandbox;

/*Generated by MPS */


public class Vector3 {
  public double x;
  public double y;
  public double z;
  public Vector3(double x, double y, double z) {
    this.x = x;
    this.y = y;
    this.z = z;
  }
  public static final Vector3 zero = new Vector3(0, 0, 0);
  public Vector3 subtract(Vector3 other) {
    return new Vector3(x - other.x, y - other.y, z - other.z);
  }
  public static Vector3 midPoint(Vector3 a, Vector3 b) {
    return new Vector3((a.x + b.x) * 0.5f, (a.y + b.y) * 0.5f, (a.z + b.z) * 0.5f);
  }
  public static Vector3 add(Vector3 a, Vector3 b) {
    return new Vector3(b.x + a.x, b.y + a.y, b.z + a.z);
  }
  public static Vector3 subtract(Vector3 a, Vector3 b) {
    return new Vector3(a.x - b.x, a.y - b.y, a.z - b.z);
  }
  public static Double distance(Vector3 a, Vector3 b) {
    return Math.sqrt((Math.pow(b.x - a.x, 2) + Math.pow(b.y - a.y, 2) + Math.pow(b.z - a.z, 2)));
  }
  @Override
  public String toString() {
    return "(" + x + "," + y + "," + z + ")";
  }
}
