package ModelTrainLanguage.sandbox;

/*Generated by MPS */

import javax.swing.JPanel;
import java.awt.image.BufferedImage;
import java.awt.Graphics2D;

public class VisualisationPanel extends JPanel {
  private int width;
  private int height;
  private BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
  private Graphics2D g = image.createGraphics();


}
