package ModelTrainLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptModelTrainSet = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.ModelTrainSet", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503fL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).childDescriptors(new ConceptDescriptorBuilder.Link(8871674439221071936L, "trackPieces", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL), true, true, false), new ConceptDescriptorBuilder.Link(8871674439221071938L, "trains", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x5e7da70e100fc394L), true, true, false), new ConceptDescriptorBuilder.Link(296972292287259082L, "stations", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea6174L), true, true, false)).children(new String[]{"trackPieces", "trains", "stations"}, new boolean[]{true, true, true}).create();
  /*package*/ final ConceptDescriptor myConceptRoute = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.Route", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea6280L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).create();
  /*package*/ final ConceptDescriptor myConceptStation = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.Station", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea6174L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(296972292287259026L, "stationTrack", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL), false, true, false)).children(new String[]{"stationTrack"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptTrack = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.Track", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptTrackCurve = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.TrackCurve", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea6264L)).super_("ModelTrainLanguage.structure.Track").super_(MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL)).parents("ModelTrainLanguage.structure.Track").parentIds(MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL)).create();
  /*package*/ final ConceptDescriptor myConceptTrackMulti = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.TrackMulti", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea61eaL)).super_("ModelTrainLanguage.structure.Track").super_(MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL)).parents("ModelTrainLanguage.structure.Track").parentIds(MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL)).childDescriptors(new ConceptDescriptorBuilder.Link(296972292287259292L, "splitPoint", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea6206L), false, false, false), new ConceptDescriptorBuilder.Link(296972292287259294L, "single", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea6206L), false, false, false), new ConceptDescriptorBuilder.Link(296972292287259297L, "multi", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea6206L), false, true, false)).children(new String[]{"splitPoint", "single", "multi"}, new boolean[]{false, false, true}).alias("", "A piece of track that represents a splitter or merger").create();
  /*package*/ final ConceptDescriptor myConceptTrackSplitter = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.TrackSplitter", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea61ceL)).super_("ModelTrainLanguage.structure.Track").super_(MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL)).parents("ModelTrainLanguage.structure.Track").parentIds(MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL)).create();
  /*package*/ final ConceptDescriptor myConceptTrackStraight = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.TrackStraight", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea6244L)).super_("ModelTrainLanguage.structure.Track").super_(MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL)).parents("ModelTrainLanguage.structure.Track").parentIds(MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL)).childDescriptors(new ConceptDescriptorBuilder.Link(296972292287224460L, "track1", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL), true, false, false), new ConceptDescriptorBuilder.Link(296972292287224462L, "track2", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL), true, false, false), new ConceptDescriptorBuilder.Link(296972292287259193L, "inPos", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea6206L), false, false, false), new ConceptDescriptorBuilder.Link(296972292287259197L, "outPos", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea6206L), false, false, false)).children(new String[]{"track1", "track2", "inPos", "outPos"}, new boolean[]{false, false, false, false}).create();
  /*package*/ final ConceptDescriptor myConceptTrain = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.Train", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x5e7da70e100fc394L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(8871674439221071913L, "trainEngine", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af5027L), false, true, false), new ConceptDescriptorBuilder.Link(8871674439221071915L, "trainCar", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af5028L), true, true, false)).children(new String[]{"trainEngine", "trainCar"}, new boolean[]{true, true}).create();
  /*package*/ final ConceptDescriptor myConceptTrainCar = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.TrainCar", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af5028L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).create();
  /*package*/ final ConceptDescriptor myConceptTrainEngine = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.TrainEngine", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af5027L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).create();
  /*package*/ final ConceptDescriptor myConceptVector = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.Vector", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x41f0eb9f5ea6206L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(296972292287259170L, "x"), new ConceptDescriptorBuilder.Prop(296972292287259172L, "y"), new ConceptDescriptorBuilder.Prop(296972292287259175L, "z")).properties("x", "y", "z").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptModelTrainSet, myConceptRoute, myConceptStation, myConceptTrack, myConceptTrackCurve, myConceptTrackMulti, myConceptTrackSplitter, myConceptTrackStraight, myConceptTrain, myConceptTrainCar, myConceptTrainEngine, myConceptVector);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0q, conceptFqName)) {
      case 0:
        return myConceptModelTrainSet;
      case 1:
        return myConceptRoute;
      case 2:
        return myConceptStation;
      case 3:
        return myConceptTrack;
      case 4:
        return myConceptTrackCurve;
      case 5:
        return myConceptTrackMulti;
      case 6:
        return myConceptTrackSplitter;
      case 7:
        return myConceptTrackStraight;
      case 8:
        return myConceptTrain;
      case 9:
        return myConceptTrainCar;
      case 10:
        return myConceptTrainEngine;
      case 11:
        return myConceptVector;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0q = new String[]{"ModelTrainLanguage.structure.ModelTrainSet", "ModelTrainLanguage.structure.Route", "ModelTrainLanguage.structure.Station", "ModelTrainLanguage.structure.Track", "ModelTrainLanguage.structure.TrackCurve", "ModelTrainLanguage.structure.TrackMulti", "ModelTrainLanguage.structure.TrackSplitter", "ModelTrainLanguage.structure.TrackStraight", "ModelTrainLanguage.structure.Train", "ModelTrainLanguage.structure.TrainCar", "ModelTrainLanguage.structure.TrainEngine", "ModelTrainLanguage.structure.Vector"};
}
