package ModelTrainLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptModelTrainSet = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.ModelTrainSet", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503fL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).childDescriptors(new ConceptDescriptorBuilder.Link(8871674439221071936L, "trackPieces", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL), true, true, false), new ConceptDescriptorBuilder.Link(8871674439221071938L, "trains", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x5e7da70e100fc394L), true, true, false)).children(new String[]{"trackPieces", "trains"}, new boolean[]{true, true}).create();
  /*package*/ final ConceptDescriptor myConceptTrack = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.Track", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(8871674439221113545L, "x1"), new ConceptDescriptorBuilder.Prop(8871674439221113554L, "x2"), new ConceptDescriptorBuilder.Prop(8871674439221113559L, "y1"), new ConceptDescriptorBuilder.Prop(8871674439221113565L, "y2"), new ConceptDescriptorBuilder.Prop(8871674439221113572L, "z1"), new ConceptDescriptorBuilder.Prop(8871674439221113580L, "z2")).properties("x1", "x2", "y1", "y2", "z1", "z2").childDescriptors(new ConceptDescriptorBuilder.Link(296972292287224460L, "track1", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL), true, false, false), new ConceptDescriptorBuilder.Link(296972292287224462L, "track2", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af503aL), true, false, false)).children(new String[]{"track1", "track2"}, new boolean[]{false, false}).create();
  /*package*/ final ConceptDescriptor myConceptTrain = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.Train", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x5e7da70e100fc394L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).childDescriptors(new ConceptDescriptorBuilder.Link(8871674439221071913L, "trainEngine", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af5027L), false, true, false), new ConceptDescriptorBuilder.Link(8871674439221071915L, "trainCar", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af5028L), true, true, false)).children(new String[]{"trainEngine", "trainCar"}, new boolean[]{true, true}).create();
  /*package*/ final ConceptDescriptor myConceptTrainCar = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.TrainCar", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af5028L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).create();
  /*package*/ final ConceptDescriptor myConceptTrainEngine = new ConceptDescriptorBuilder("ModelTrainLanguage.structure.TrainEngine", MetaIdFactory.conceptId(0xe93fac6b76ff4453L, 0xa26793a92c7c2879L, 0x7b1e84e5f8af5027L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptModelTrainSet, myConceptTrack, myConceptTrain, myConceptTrainCar, myConceptTrainEngine);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0j, conceptFqName)) {
      case 0:
        return myConceptModelTrainSet;
      case 1:
        return myConceptTrack;
      case 2:
        return myConceptTrain;
      case 3:
        return myConceptTrainCar;
      case 4:
        return myConceptTrainEngine;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0j = new String[]{"ModelTrainLanguage.structure.ModelTrainSet", "ModelTrainLanguage.structure.Track", "ModelTrainLanguage.structure.Train", "ModelTrainLanguage.structure.TrainCar", "ModelTrainLanguage.structure.TrainEngine"};
}
