package ModelTrainLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.lang.editor.cellProviders.RefCellCellProvider;
import jetbrains.mps.nodeEditor.InlineCellProvider;

public class Train_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_xsxrky_a(editorContext, node);
  }
  private EditorCell createCollection_xsxrky_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_xsxrky_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_xsxrky_a0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_xsxrky_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xsxrky_c0(editorContext, node));
    editorCell.addEditorCell(this.createRefCell_xsxrky_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xsxrky_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xsxrky_f0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xsxrky_g0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xsxrky_h0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_xsxrky_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Name: ");
    editorCell.setCellId("Constant_xsxrky_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_xsxrky_b0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_name");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_xsxrky_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " Route: ");
    editorCell.setCellId("Constant_xsxrky_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefCell_xsxrky_d0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefCellCellProvider(node, editorContext);
    provider.setRole("currentRoute");
    provider.setNoTargetText("<no currentRoute>");
    EditorCell editorCell;
    provider.setAuxiliaryCellProvider(new Train_Editor._Inline_xsxrky_a3a());
    editorCell = provider.createEditorCell(editorContext);
    if (editorCell.getRole() == null) {
      editorCell.setReferenceCell(true);
      editorCell.setRole("currentRoute");
    }
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  public static class _Inline_xsxrky_a3a extends InlineCellProvider {
    public _Inline_xsxrky_a3a() {
      super();
    }
    public EditorCell createEditorCell(EditorContext editorContext) {
      return this.createEditorCell(editorContext, this.getSNode());
    }
    public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
      return this.createProperty_xsxrky_a0d0(editorContext, node);
    }
    private EditorCell createProperty_xsxrky_a0d0(EditorContext editorContext, SNode node) {
      CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
      provider.setRole("name");
      provider.setNoTargetText("<no name>");
      provider.setReadOnly(true);
      EditorCell editorCell;
      editorCell = provider.createEditorCell(editorContext);
      editorCell.setCellId("property_name_1");
      editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
      SNode attributeConcept = provider.getRoleAttribute();
      Class attributeKind = provider.getRoleAttributeClass();
      if (attributeConcept != null) {
        EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
        return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
      } else
      return editorCell;
    }
  }
  private EditorCell createConstant_xsxrky_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "  TrainEngine: ");
    editorCell.setCellId("Constant_xsxrky_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xsxrky_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Default");
    editorCell.setCellId("Constant_xsxrky_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xsxrky_g0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "  TrainCars: ");
    editorCell.setCellId("Constant_xsxrky_g0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_xsxrky_h0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "0");
    editorCell.setCellId("Constant_xsxrky_h0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
